version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_SQL_PASSWORD}

  app-projet3:
    image: projet3
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      MY_SQL_PASSWORD: ${MY_SQL_PASSWORD}
      MY_SQL_USERNAME: ${MY_SQL_USERNAME}
