
server:
  port: 8080
  servlet:
    context-path: /api/

app:
  base:
    path: /dev_school_projects/project3OC/pictures/

spring:
  main:
    allow-circular-references: true

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/projet3OC?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  file:
    name: logs/logfile.log
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
